-- 1. Create the Customers table
CREATE TABLE Customers (
    CustomerID SERIAL PRIMARY KEY,
    CustomerName TEXT,
    ContactName  TEXT,
    Address      TEXT,
    City         TEXT,
    PostalCode   TEXT,
    Country      TEXT
);

-- 2. Insert the provided rows
INSERT INTO Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES
(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany'),
(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '05021', 'Mexico'),
(3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '05023', 'Mexico'),
(4, 'Around the Horn', 'Thomas Hardy', '120 Hanover Sq.', 'London', 'WA1 1DP', 'UK'),
(5, 'Berglunds snabbköp', 'Christina Berglund', 'Berguvsvägen 8', 'Luleå', 'S-958 22', 'Sweden'),
(6, 'Blauer See Delikatessen', 'Hanna Moos', 'Forsterstr. 57', 'Mannheim', '68306', 'Germany'),
(7, 'Blondel père et fils', 'Frédérique Citeaux', '24, place Kléber', 'Strasbourg', '67000', 'France'),
(8, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain'),
(9, 'Bon app', 'Elizabeth Lincoln', '12, rue des Bouchers', 'Marseille', '13008', 'France'),
(10, 'Bottom-Dollar Marketse', 'Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen', 'T2F 8M4', 'Canada'),
(11, 'Bólido Comidas preparadas', 'Martín Sommer', 'C/ Araquil, 67', 'Madrid', '28023', 'Spain'),
(12, 'Cactus Comidas preparadas', 'Patricio Simpson', 'Cerrito 333', 'Buenos Aires', '1010', 'Argentina'),
(13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '05022', 'Mexico'),
(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland'),
(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil'),
(16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12  Brewery', 'London', 'WX1 6LT', 'UK'),
(17, 'Drachenblut Delikatessen', 'Sven Ottlieb', 'Walserweg 21', 'Aachen', '52066', 'Germany'),
(18, 'Du monde entier', 'Janine Labrune', '67, rue des Cinquante Otages', 'Nantes', '44000', 'France'),
(19, 'Eastern Connection', 'Ann Devon', '35 King George', 'London', 'WX3 6FW', 'UK'),
(20, 'Ernst Handel', 'Roland Mendel', 'Kirchgasse 6', 'Graz', '8010', 'Austria'),
(21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil'),
(22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain'),
(23, 'Folies gourmandes', 'Martine Rancé', '184, chaussée de Tournai', 'Lille', '59000', 'France'),
(24, 'Franchi S.p.A.', 'Paolo Accorti', 'Via Monte Bianco 34', 'Torino', '10100', 'Italy'),
(25, 'Frankenversand', 'Peter Franken', 'Berliner Platz 43', 'München', '80805', 'Germany'),
(26, 'France restauration', 'Carine Schmitt', '54, rue Royale', 'Nantes', '44000', 'France'),
(27, 'Furia Bacalhau', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal'),
(28, 'Galeria del gastronómo', 'Eduardo Saavedra', 'Rambla de Cataluña, 23', 'Barcelona', '8022', 'Spain'),
(29, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain'),
(30, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil'),
(31, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA'),
(32, 'GROSELLA-Restaurante', 'Manuel Pereira', '5ª Ave. Los Palosgrandes', 'Caracas', '1081', 'Venezuela'),
(33, 'Hanari Carnes', 'Mario Barbosa', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil'),
(34, 'HILARIÓN-Abastos', 'Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', '5022', 'Venezuela'),
(35, 'Nordic Trading', 'Lars Peterson', 'Hovedgade 15', 'Copenhagen', '2100', 'Denmark'),
(36, 'Paris Délices', 'Marie Bertrand', '25 Rue de la République', 'Paris', '75001', 'France'),
(37, 'Tokyo Traders', 'Yoshi Nagase', '9-8 Sekimai Musashino-shi', 'Tokyo', '100-0014', 'Japan'),
(38, 'Sydney Seafood', 'Michael Barnes', '456 George Street', 'Sydney', '2000', 'Australia'),
(39, 'Amsterdam Deli', 'Jan de Vries', 'Damrak 277', 'Amsterdam', '1012', 'Netherlands'),
(40, 'Milano Fine Foods', 'Giuseppe Romano', 'Via Dante 53', 'Milan', '20123', 'Italy'),
(41, 'Dublin Pub & Kitchen', 'Sean O''Connor', '42 Temple Bar', 'Dublin', 'D02 YH76', 'Ireland'),
(42, 'Stockholm Delicatessen', 'Eva Lundgren', 'Drottninggatan 89', 'Stockholm', '111 60', 'Sweden'),
(43, 'Vienna Coffee House', 'Franz Weber', 'Kärntner Straße 12', 'Vienna', '1010', 'Austria'),
(44, 'Lisboa Vinhos', 'Manuel Silva', 'Rua Augusta 165', 'Lisbon', '1100-048', 'Portugal'),
(45, 'Barcelona Tapas', 'Carmen Rodriguez', 'Las Ramblas 222', 'Barcelona', '08002', 'Spain'),
(46, 'Brussels Chocolatier', 'Pierre Dubois', 'Grand Place 5', 'Brussels', '1000', 'Belgium'),
(47, 'Oslo Fish Market', 'Erik Hansen', 'Storgata 45', 'Oslo', '0182', 'Norway'),
(48, 'Athens Olive Oil', 'Nikos Papadopoulos', 'Ermou 88', 'Athens', '105 63', 'Greece'),
(49, 'Warsaw Deli', 'Anna Kowalski', 'Nowy Świat 44', 'Warsaw', '00-363', 'Poland'),
(50, 'Prague Beer Garden', 'Josef Novak', 'Václavské náměstí 21', 'Prague', '110 00', 'Czech Republic'),
(51, 'Budapest Paprika', 'Zsolt Nagy', 'Váci utca 33', 'Budapest', '1052', 'Hungary'),
(52, 'Moscow Caviar', 'Ivan Petrov', 'Tverskaya Street 15', 'Moscow', '125009', 'Russia'),
(53, 'Beijing Duck House', 'Li Wei', 'Wangfujing Street 88', 'Beijing', '100006', 'China'),
(54, 'Seoul Kimchi', 'Park Min-ji', 'Gangnam-daero 162', 'Seoul', '06120', 'South Korea'),
(55, 'Bangkok Spices', 'Somchai Suk', 'Sukhumvit Soi 55', 'Bangkok', '10110', 'Thailand'),
(56, 'Singapore Seafood', 'Lee Kuan', 'Orchard Road 313', 'Singapore', '238895', 'Singapore'),
(57, 'Mumbai Curry House', 'Raj Patel', 'Colaba Causeway 28', 'Mumbai', '400005', 'India'),
(58, 'Dubai Dates', 'Ahmed Al-Sayed', 'Sheikh Zayed Road 155', 'Dubai', '12345', 'UAE'),
(59, 'Cape Town Wines', 'John Smith', 'Long Street 123', 'Cape Town', '8001', 'South Africa'),
(60, 'Buenos Aires Steaks', 'Diego Martinez', 'Avenida de Mayo 825', 'Buenos Aires', '1084', 'Argentina'),
(61, 'Santiago Seafood', 'Carlos Ruiz', 'Providencia 2233', 'Santiago', '7510000', 'Chile'),
(62, 'Lima Ceviche', 'Ana Garcia', 'Av. La Marina 1000', 'Lima', '15084', 'Peru'),
(63, 'Bogota Coffee', 'Juan Rodriguez', 'Carrera 7 #72-41', 'Bogota', '110221', 'Colombia'),
(64, 'Mexico City Tacos', 'Roberto Sanchez', 'Paseo de la Reforma 222', 'Mexico City', '06600', 'Mexico'),
(65, 'Toronto Maple', 'Sarah Johnson', '200 Bay Street', 'Toronto', 'M5J 2J2', 'Canada'),
(66, 'Vancouver Sushi', 'David Lee', 'Robson Street 1133', 'Vancouver', 'V6E 1B5', 'Canada'),
(67, 'Chicago Deep Dish', 'Mike Williams', '233 S Wacker Dr', 'Chicago', '60606', 'USA'),
(68, 'New York Deli', 'Rachel Green', '350 5th Avenue', 'New York', '10118', 'USA'),
(69, 'San Francisco Sourdough', 'Tom Wilson', '1 Ferry Building', 'San Francisco', '94111', 'USA'),
(70, 'Seattle Coffee', 'Emma Brown', 'Pike Place 85', 'Seattle', '98101', 'USA'),
(71, 'Melbourne Coffee', 'James Wilson', 'Collins Street 447', 'Melbourne', '3000', 'Australia'),
(72, 'Auckland Fish Market', 'Emma Thompson', 'Queen Street 85', 'Auckland', '1010', 'New Zealand'),
(73, 'Rome Pasta', 'Marco Rossi', 'Via del Corso 112', 'Rome', '00186', 'Italy'),
(74, 'Naples Pizza', 'Luigi Marino', 'Via Toledo 55', 'Naples', '80132', 'Italy'),
(75, 'Florence Wines', 'Andrea Conti', 'Via dei Calzaiuoli 65', 'Florence', '50122', 'Italy'),
(76, 'Hamburg Fish Market', 'Hans Schmidt', 'Reeperbahn 153', 'Hamburg', '20359', 'Germany'),
(77, 'Munich Biergarten', 'Klaus Weber', 'Karlsplatz 1', 'Munich', '80335', 'Germany'),
(78, 'Lyon Gastronomy', 'Philippe Martin', 'Rue de la République 86', 'Lyon', '69002', 'France'),
(79, 'Nice Mediterranean', 'Sophie Dubois', 'Promenade des Anglais 49', 'Nice', '06000', 'France'),
(80, 'Bordeaux Wines', 'Jean-Pierre Blanc', 'Cours de l''Intendance 50', 'Bordeaux', '33000', 'France'),
(81, 'Manchester Pies', 'William Brown', NULL, 'Manchester', 'M1 1PW', 'UK'),
(82, 'Edinburgh Whisky', 'Angus MacLeod', NULL, 'Edinburgh', 'EH1 1SG', 'UK'),
(83, 'Liverpool Docks', 'George Harrison', 'Albert Dock 12', 'Liverpool', 'L3 4AA', 'UK'),
(84, 'Helsinki Market', 'Matti Virtanen', 'Mannerheimintie 13', 'Helsinki', '00100', 'Finland'),
(85, 'Reykjavik Fish', 'Björk Gudmundsdottir', 'Laugavegur 55', 'Reykjavik', '101', 'Iceland'),
(86, 'Tel Aviv Hummus', 'David Cohen', 'Dizengoff Street 150', 'Tel Aviv', '6433222', 'Israel'),
(87, 'Marrakech Spices', 'Hassan El Amrani', 'Jamaa el-Fna 1', 'Marrakech', '40000', 'Morocco'),
(88, 'Cairo Bazaar', 'Mohammed Ahmed', 'Khan el-Khalili', 'Cairo', '11511', 'Egypt'),
(89, 'Istanbul Kebab', 'Mehmet Yilmaz', 'Istiklal Caddesi 123', 'Istanbul', '34435', 'Turkey'),
(90, 'Beirut Mezze', 'Samir Khalil', 'Hamra Street 44', 'Beirut', '11-2810', 'Lebanon'),
(91, 'Rio Churrascaria', 'Pedro Santos', 'Copacabana Beach 100', 'Rio de Janeiro', '22070-002', 'Brazil'),
(92, 'Salvador Acarajé', 'Maria Oliveira', 'Pelourinho 55', 'Salvador', '40301-110', 'Brazil'),
(93, 'Cusco Andean', 'Miguel Torres', NULL, 'Cusco', '08002', 'Peru'),
(94, 'Havana Café', 'José Rodriguez', NULL, 'Havana', '10100', 'Cuba'),
(95, 'San Juan Mofongo', 'Carmen Vega', 'Calle del Cristo 207', 'San Juan', '00901', 'Puerto Rico'),
(96, 'Panama Fresh Market', 'Roberto Diaz', 'Calle 50 Final', 'Panama City', '0801', 'Panama'),
(97, 'Manila Seafood', 'Maria Santos', 'Bonifacio High Street', 'Manila', '1634', 'Philippines'),
(98, 'Jakarta Spice Market', 'Siti Widodo', 'Jalan Thamrin 10', 'Jakarta', '10230', 'Indonesia'),
(99, 'Ho Chi Minh Pho', 'Nguyen Van', 'Le Loi Street 15', 'Ho Chi Minh City', '700000', 'Vietnam'),
(100, 'Kuala Lumpur Street Food', 'Lee Ming', 'Jalan Alor', 'Kuala Lumpur', '50200', 'Malaysia'),
(101, 'Taipei Night Market', 'Chen Wei', 'Shilin Night Market', 'Taipei', '111', 'Taiwan'),
(102, 'Hong Kong Dim Sum', 'Wong Lee', 'Nathan Road 228', 'Hong Kong', '999077', 'Hong Kong'),
(103, 'Macau Casino Foods', 'Liu Chan', 'Cotai Strip 888', 'Macau', '999078', 'Macau'),
(104, 'Osaka Sushi', 'Tanaka Hiroshi', 'Dotonbori 1-1', 'Osaka', '542-0071', 'Japan'),
(105, 'Kyoto Traditional', 'Suzuki Kenji', 'Gion District 55', 'Kyoto', '605-0073', 'Japan'),
(106, 'Busan Fish Market', 'Kim Young-ho', 'Jagalchi Market 88', 'Busan', '48994', 'South Korea'),
(107, 'Shanghai Dumplings', 'Zhang Wei', 'Nanjing Road 123', 'Shanghai', '200001', 'China'),
(108, 'Guangzhou Cuisine', 'Lin Feng', 'Beijing Road 99', 'Guangzhou', '510000', 'China'),
(109, 'Chengdu Hotpot', 'Wang Lei', 'Chunxi Road 55', 'Chengdu', '610000', 'China'),
(110, 'Hanoi Street Food', 'Tran Hung', 'Old Quarter 36', 'Hanoi', '100000', 'Vietnam'),
(111, 'Delhi Curry House', 'Amit Kumar', 'Connaught Place E-12', 'New Delhi', '110001', 'India'),
(112, 'Bangalore Tech Café', 'Priya Sharma', 'MG Road 78', 'Bangalore', '560001', 'India'),
(113, 'Chennai Masala', 'Ravi Krishnan', 'Marina Beach Road 45', 'Chennai', '600001', 'India'),
(114, 'Colombo Spices', 'Kumar Perera', 'Galle Road 123', 'Colombo', '00100', 'Sri Lanka'),
(115, 'Kathmandu Kitchen', 'Ram Thapa', 'Thamel Marg 55', 'Kathmandu', '44600', 'Nepal'),
(116, 'Dhaka Biryani', 'Abdul Rahman', 'Gulshan Avenue 75', 'Dhaka', '1212', 'Bangladesh'),
(117, 'Karachi Grill', 'Hassan Ali', 'Zamzama Boulevard 88', 'Karachi', '75500', 'Pakistan'),
(118, 'Lahore Food Street', 'Fatima Khan', NULL, 'Lahore', '54000', 'Pakistan'),
(119, 'Kabul Kebab', 'Ahmad Zahir', NULL, 'Kabul', '1001', 'Afghanistan'),
(120, 'Tehran Cuisine', 'Reza Ahmadi', NULL, 'Tehran', '11369', 'Iran'),
(121, 'Kuwait City Dates', 'Abdullah Al-Salem', 'Gulf Road 66', 'Kuwait City', '15300', 'Kuwait'),
(122, 'Doha Pearls', 'Mohammed Al-Thani', 'Corniche Street 99', 'Doha', '23133', 'Qatar'),
(123, 'Manama Market', 'Ali Al-Bahrani', 'Seef District 77', 'Manama', '11111', 'Bahrain'),
(124, 'Muscat Fish Market', 'Said Al-Said', 'Muttrah Corniche 44', 'Muscat', '100', 'Oman'),
(125, 'Riyadh Dates', 'Abdullah Al-Saud', 'Olaya Street 88', 'Riyadh', '12214', 'Saudi Arabia'),
(126, 'Amman Falafel', 'Omar Al-Hussein', 'Rainbow Street 33', 'Amman', '11181', 'Jordan'),
(127, 'Damascus Kitchen', 'Fadi Al-Assad', 'Straight Street 77', 'Damascus', '11111', 'Syria'),
(128, 'Baghdad Market', 'Karim Al-Iraqi', 'Karrada Street 55', 'Baghdad', '10011', 'Iraq'),
(129, 'Baku Caviar', 'Eldar Aliyev', 'Nizami Street 90', 'Baku', 'AZ1000', 'Azerbaijan'),
(130, 'Tbilisi Wine', 'Giorgi Kvaratskhelia', 'Rustaveli Avenue 40', 'Tbilisi', '0108', 'Georgia'),
(131, 'Yerevan Brandy', 'Armen Sargsyan', 'Northern Avenue 21', 'Yerevan', '0001', 'Armenia'),
(132, 'Tashkent Plov', 'Timur Uzbekov', 'Amir Temur Street 107', 'Tashkent', '100084', 'Uzbekistan'),
(133, 'Almaty Apples', 'Nursultan Kazakh', 'Dostyk Avenue 85', 'Almaty', '050000', 'Kazakhstan'),
(134, 'Ashgabat Market', 'Gurbanguly Berdimuhamedow', 'Independence Square 44', 'Ashgabat', '744000', 'Turkmenistan');

